/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ter00942' at '06/08/16 14:24' with Gradle 2.14.1
 *
 * @author ter00942, @date 06/08/16 14:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
